application: kitekbot27
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
  mime_type: vnd.microsoft.icon
- url: /js/(.*\.js)
  static_files: static/js/\1
  upload: static/js/(.*\.js)
- url: /css/(.*\.css)
  static_files: static/css/\1
  upload: static/css/(.*\.css)
- url: /img/(.*\.png)
  static_files: static/images/\1
  upload: static/images/(.*\.png)
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "latest"
- name: jinja2
  version: "latest"


inbound_services:
- xmpp_subscribe
- xmpp_message
- xmpp_presence
- warmup
