application: kitekbot
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /cron/.*
  script: bot.py
  login: admin

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  mime_type: vnd.microsoft.icon
  upload: static/images/favicon\.ico

- url: /css/(.*\.css)
  static_files: static/css/\1
  upload: static/css/(.*\.css)
  
- url: /img/(.*\.(png|gif|jpg))
  static_files: static/images/\1
  upload: static/images/(.*\.(png|gif|jpg))

- url: /img/chats/(.*\.(png|gif|jpg))
  static_files: static/images/chats/\1
  upload: static/images/chats/(.*\.(png|gif|jpg))

- url: /js/(.*\.js)
  static_files: static/js/\1
  upload: static/js/(.*\.js)
  
- url: /.*
  script: bot.py


inbound_services:
- xmpp_message
- xmpp_subscribe
- xmpp_presence
- warmup
